config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show], param: :slug, path: '/user'

  resources :carts
  resources :line_items
  resources :products, only: %i[index show]

  get 'checkout', to: 'checkouts#show'
  get 'billing', to: 'billing#show'

  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def update_quantity
    @line_item.update_attribute(:quantity)
  end
end

app/models/concerns/current_cart.rb
module CurrentCart
  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price.to_i * quantity.to_i
  end
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_any_line_item
  has_many :line_items, dependent: :destroy

  private

  def not_referenced_any_line_item
    unless line_items.empty?
      errors.add(:base, "Line items present")
      throw :abort
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Pay::Billable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_person_name
  has_one_attached :avatar

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CurrentCart
  before_action :set_cart
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name avatar])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: %i[show edit update destroy]

  def index
    @carts = Cart.all
  end

  def show
  end

  def new
    @cart = Cart.new
  end

  def edit
  end

  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to carts_url, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_cart
    @cart = Cart.find(params[:id])
  end

  def cart_params
    params.fetch(:cart, {})
  end

  def invalid_cart
    logger.error "Attempt to access invalid cart #{params[:id]}"
    redirect_to root_path, notice: "That cart doesn't exist"
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!

  def show
    current_user.processor = :stripe
    current_user.customer

    @checkout_session = current_user.payment_processor.checkout(
      mode: "payment",
      line_items: [
        quantity: 1,
        name: course.name,
        amount: (course.price * 100).to_i,
        currency: "USD",
        description: course.description
      ]
    )
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_line_item, only: %i[show edit update destroy]
  before_action :set_cart, only: [:create]

  def index
    @line_items = LineItem.all
  end

  def show
  end

  def new
    @line_item = LineItem.new
  end

  def edit
  end

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.cart, notice: "Item added to cart." }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item.cart, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart = Cart.find(session[:cart_id])
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_path(@cart), notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  def line_item_params
    params.require(:line_item).permit(:product_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show]

  def index
    @products = Product.all
  end

  def show
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.friendly.find(params[:slug])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url_for(user, opts = {})
    size = opts[:size] || 32

    if user.avatar.attached?
      user.avatar.variant(
        resize: "#{size}x#{size}!"
      )
    else
      hash = Digest::MD5.hexdigest(user.email.downcase)
      "https://secure.gravatar.com/avatar/#{hash}.png?s=#{size}"
    end
  end

  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="d-flex justify-content-end mt-3">
  <%= link_to "Keep Shopping", products_path, class: "btn btn-warning" %>
</div>

<section>
  <div class="pt-3">
    <h5 class="mb-3">Shopping Cart</h5>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Item</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        <th scope="col">Taxes</th>
        <th scope="col">Total</th>
        <th scope="col">Action</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      <%= render(@cart.line_items) %>
    </tbody>
  </table>

  <div class="d-flex justify-content-between">
    <div>
      <%= button_to 'Empty Cart', @cart, method: :delete, data: { confirm: "Are you sure? " }, class: "btn btn-danger" %>
    </div>
    <div>
      <h4>
        <span>Total: </span><%= number_to_currency(@cart.total_price) %>
      </h4>
    </div>
  </div>
</section>

<div class="mt-5">
  <%= link_to 'Edit', edit_cart_path(@cart) %> |
  <%= link_to 'Back', carts_path %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <title>RailsShopApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
</head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/notices" %>

  <div class="container" role="main">

    <%= yield %>
  </div>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<tr>
  <td>
    <%= form_with model: line_item do |f| %>
      <%= f.number_field :quantity, class: "form-control", style: "width: 75px" %>
      <%= f.submit "Update", method: :patch %>
    <% end %>
  </td>
  <td>
    <span>
      <%= link_to product_path(line_item.product) do %>
        <%= truncate(line_item.product.title, length: 20) %>
      <% end %>
    </span>
    <figure class="product-image__cart">
      <%= image_tag(line_item.product.image) %>
    </figure>
  </td>
  <td><%= number_to_currency(line_item.product.price) %></td>
  <td><%= number_to_currency(0) %></td>
  <td><%= number_to_currency(line_item.total_price) %></td>
  <td><%= link_to 'Remove Item', line_item, method: :delete, data: { confirm: "Are you sure? " }, class: "btn btn-sm btn-outline-danger" %></td>
  <td><%= link_to 'Remove Item', "#", method: :delete, data: { confirm: "Are you sure? " }, class: "btn btn-sm btn-success" %></td>
</tr>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/products/_product.html.erb
<div class="col-md-4 col-sm-6 col-xs-12">
  <div class="card-deck">
    <div class="card my-4 shadow">
      <%= link_to product_path(product.id), "aria-label": "Read more about #{product.title}" do %>
        <div class="img-fluid product-image">
          <%= image_tag product.image, class: "card-img-top p-1", alt: "#{product.title} product Image" %>
        </div>
      <% end %>
      <div class="card-body">
        <p class="card-title fs-5 text-nowrap overflow-hidden text-truncate "><%= product.title %></p>
        <span class="badge rounded-pill bg-warning text-capitalize text-dark"><%= product.category %></span>
        <p class="card-text"><%= product.description.truncate(150) %></p>
        <div class="py-1 d-flex justify-content-between align-content-center">
          <strong class="align-self-center"><%= number_to_currency(product.price) %></strong>
          <button class="btn btn-primary">Add to Cart</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<div class="container">
  <div class="row">
    <%= render @products %>
  </div>
</div>

<!--<div class="d-flex justify-content-center my-4">-->
  <%#== pagy_bootstrap_nav(@pagy) %>
<!--</div>-->

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>

<div><%= @product.title %></div>
add product quantity
<div><%= button_to "Add to Cart", line_items_path(product_id: @product.id) %></div>

app/views/shared/_form_errors.html.erb
<% if f.object.errors.any? %>
  <div id="form_errors" class="alert alert-danger">
    <h5>
      <%= pluralize(f.object.errors.count, "error") %> prevented this <%= f.object.class.name.downcase %> from being
      saved:
    </h5>
    <ul>
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <%= link_to "Rails Shop", root_path, class: "navbar-brand" %>
    <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "About", root_path, class: "nav-link", "aria-current": "page" %></li>
        <li class="nav-item"><%= link_to "Contact", root_path, class: "nav-link", "aria-current": "page" %></li>
        <li class="nav-item"><%= link_to "Categories ", root_path, class: "nav-link", "aria-current": "page" %></li>
        <li class="nav-item"><%= link_to "Searchbar ", root_path, class: "nav-link", "aria-current": "page" %></li>
      </ul>

    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
  <div class="container-fluid">
    <%= link_to "Rails Shop", root_path, class: "navbar-brand" %>
    <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "About", root_path, class: "nav-link", "aria-current": "page" %></li>
        <li class="nav-item"><%= link_to "Contact", root_path, class: "nav-link", "aria-current": "page" %></li>
        <li class="nav-item"><%= link_to "Categories ", root_path, class: "nav-link", "aria-current": "page" %></li>
        <li class="nav-item"><%= link_to "Searchbar ", root_path, class: "nav-link", "aria-current": "page" %></li>
      </ul>
      <ul class="navbar-nav justify-content-end">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to user_path(current_user.slug), class: "nav-link", "aria-current": "page" do %>
              <%= image_tag avatar_url_for(current_user, size: 40), height: 20, width: 20, class: "rounded mr-3" %>
              <%= current_user.name.first %>
            <% end %>
          </li>
          Avatar
          <li class="nav-item"><%= link_to "Profile", user_path(current_user.slug), class: "nav-link", "aria-current": "page" %></li>
          <li class="nav-item"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link", "aria-current": "page" %></li>
        <% else %>
          <li class="nav-item"><%= link_to "Log in", new_user_session_path, class: "nav-link", "aria-current": "page" %></li>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link", "aria-current": "page" %></li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %> alert-dismissible fade show" role="alert">
    <div class="container">
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="d-flex align-items-center justify-content-center mt-5">
  <div class="media mr-5 align-self-start">
    <%= image_tag avatar_url_for(current_user, size: 128), class: "rounded-circle mr-4" %>
  </div>
  <div class="media">
    <div class="media-body">
      <div class="d-flex flex-row align-items-center justify-content-between">
        <h1><%= current_user.name %></h1>
        <%= link_to "Edit", edit_user_registration_path, class: "ml-3 btn btn-secondary btn-sm" if current_user.id == @user.id %>

      </div>
    </div>
  </div>
</div>